import type { Category } from './types'

export const DEFAULT_CATEGORIES: Omit<Category, 'id' | 'listing_count'>[] = [
  {
    name: 'Restaurants & Dining',
    slug: 'restaurants-dining',
    icon: '🍽️',
    description: 'Eat in, take out, or delivery',
    display_order: 1,
  },
  {
    name: 'Auto Repair & Service',
    slug: 'auto-repair-service',
    icon: '🔧',
    description: 'Mechanics, body shops & tires',
    display_order: 2,
  },
  {
    name: 'Home Services',
    slug: 'home-services',
    icon: '🏠',
    description: 'Plumbers, electricians & more',
    display_order: 3,
  },
  {
    name: 'Health & Wellness',
    slug: 'health-wellness',
    icon: '💚',
    description: 'Doctors, therapists & clinics',
    display_order: 4,
  },
  {
    name: 'Beauty & Personal Care',
    slug: 'beauty-personal-care',
    icon: '✂️',
    description: 'Salons, spas & barbers',
    display_order: 5,
  },
  {
    name: 'Shopping & Retail',
    slug: 'shopping-retail',
    icon: '🛍️',
    description: 'Boutiques, gifts & everyday goods',
    display_order: 6,
  },
  {
    name: 'Legal & Financial',
    slug: 'legal-financial',
    icon: '⚖️',
    description: 'Attorneys, accountants & advisors',
    display_order: 7,
  },
  {
    name: 'Daycares & Education',
    slug: 'daycares-education',
    icon: '🎒',
    description: 'Child care, tutoring & schools',
    display_order: 8,
  },
  {
    name: 'Real Estate',
    slug: 'real-estate',
    icon: '🏡',
    description: 'Agents, rentals & property mgmt',
    display_order: 9,
  },
  {
    name: 'Pet Services',
    slug: 'pet-services',
    icon: '🐾',
    description: 'Vets, groomers & boarding',
    display_order: 10,
  },
  {
    name: 'Medical & Dental',
    slug: 'medical-dental',
    icon: '🏥',
    description: 'Physicians, dentists & specialists',
    display_order: 11,
  },
  {
    name: 'Gyms & Fitness',
    slug: 'gyms-fitness',
    icon: '🏋️',
    description: 'Gyms, studios & personal trainers',
    display_order: 12,
  },
  {
    name: 'Entertainment & Events',
    slug: 'entertainment-events',
    icon: '🎉',
    description: 'Fun, venues & things to do',
    display_order: 13,
  },
  {
    name: 'Construction & Contractors',
    slug: 'construction-contractors',
    icon: '🔨',
    description: 'Builders, remodelers & trades',
    display_order: 14,
  },
  {
    name: 'Cleaning Services',
    slug: 'cleaning-services',
    icon: '🧹',
    description: 'House, office & specialty cleaning',
    display_order: 15,
  },
  {
    name: 'Professional Services',
    slug: 'professional-services',
    icon: '💼',
    description: 'Consultants, staffing & business',
    display_order: 16,
  },
  {
    name: 'Technology & IT',
    slug: 'technology-it',
    icon: '💻',
    description: 'Repair, support & tech solutions',
    display_order: 17,
  },
  {
    name: 'Grocery & Food Stores',
    slug: 'grocery-food-stores',
    icon: '🛒',
    description: 'Grocers, specialty & farm markets',
    display_order: 18,
  },
]
